# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reporter.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(567, 496)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 40, 453, 366))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.name_box = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name_box.setObjectName("name_box")
        self.gridLayout.addWidget(self.name_box, 0, 2, 1, 1)
        self.condition_right = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.condition_right.setObjectName("condition_right")
        self.gridLayout.addWidget(self.condition_right, 6, 3, 1, 1)
        self.name_indicator = QtWidgets.QLabel(self.gridLayoutWidget)
        self.name_indicator.setObjectName("name_indicator")
        self.gridLayout.addWidget(self.name_indicator, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 1, 1, 1)
        self.number_indicator = QtWidgets.QLabel(self.gridLayoutWidget)
        self.number_indicator.setObjectName("number_indicator")
        self.gridLayout.addWidget(self.number_indicator, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.condition_wrong = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.condition_wrong.setObjectName("condition_wrong")
        self.gridLayout.addWidget(self.condition_wrong, 6, 2, 1, 1)
        self.state_indicator = QtWidgets.QLabel(self.gridLayoutWidget)
        self.state_indicator.setObjectName("state_indicator")
        self.gridLayout.addWidget(self.state_indicator, 6, 0, 1, 1)
        self.number_box = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.number_box.setObjectName("number_box")
        self.gridLayout.addWidget(self.number_box, 1, 2, 1, 1)
        self.error_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.error_box.setEnabled(True)
        self.error_box.setObjectName("error_box")
        self.gridLayout.addWidget(self.error_box, 8, 2, 1, 1)
        self.error_indicator = QtWidgets.QLabel(self.gridLayoutWidget)
        self.error_indicator.setEnabled(True)
        self.error_indicator.setObjectName("error_indicator")
        self.gridLayout.addWidget(self.error_indicator, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 0, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(70, 420, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.confirm = QtWidgets.QPushButton(Dialog)
        self.confirm.setGeometry(QtCore.QRect(430, 440, 90, 32))
        self.confirm.setObjectName("confirm")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(70, 450, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.device_state = QtWidgets.QLabel(Dialog)
        self.device_state.setGeometry(QtCore.QRect(150, 450, 71, 16))
        self.device_state.setObjectName("device_state")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.condition_right.setText(_translate("Dialog", "良好"))
        self.name_indicator.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "学号"))
        self.label.setText(_translate("Dialog", "姓名"))
        self.label_5.setText(_translate("Dialog", "故障描述（可选）"))
        self.number_indicator.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "仪器状况"))
        self.condition_wrong.setText(_translate("Dialog", "故障"))
        self.state_indicator.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.error_indicator.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">实验千万条  安全第一条  登记不到位  同事两行泪 </span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "带红色※ 号的都是必填项目喔"))
        self.confirm.setText(_translate("Dialog", "确定"))
        self.label_10.setText(_translate("Dialog", "安捷伦状态："))
        self.device_state.setText(_translate("Dialog", "未开启"))


import reporter_rc
