# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reporter.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(567, 496)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 40, 453, 366))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.error_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.error_box.setObjectName("error_box")
        self.gridLayout.addWidget(self.error_box, 7, 2, 1, 1)
        self.number_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.number_box.setObjectName("number_box")
        self.gridLayout.addWidget(self.number_box, 1, 2, 1, 1)
        self.condition_right = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.condition_right.setObjectName("condition_right")
        self.gridLayout.addWidget(self.condition_right, 6, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.name_box = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.name_box.setMaximumSize(QtCore.QSize(272, 16777215))
        self.name_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_box.setLineWidth(1)
        self.name_box.setObjectName("name_box")
        self.gridLayout.addWidget(self.name_box, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.condition_wrong = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.condition_wrong.setObjectName("condition_wrong")
        self.gridLayout.addWidget(self.condition_wrong, 6, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 0, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(70, 420, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.confirm = QtWidgets.QPushButton(Dialog)
        self.confirm.setGeometry(QtCore.QRect(430, 440, 90, 32))
        self.confirm.setObjectName("confirm")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.condition_right.setText(_translate("Dialog", "良好"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "学号"))
        self.label.setText(_translate("Dialog", "姓名"))
        self.label_5.setText(_translate("Dialog", "故障描述（可选）"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "仪器状况"))
        self.condition_wrong.setText(_translate("Dialog", "故障"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">实验千万条  安全第一条  登记不到位  同事两行泪 </span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "带红色※ 号的都是必填项目喔"))
        self.confirm.setText(_translate("Dialog", "确定"))

